<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- choose -' => '- válassz -',
    'Are you sure?' => 'Biztos vagy benne?',
    'Are you sure? Every data belongs this group will be deleted!' => 'Biztos vagy benne? Minden - a csoporthoz tartozó - adat törlődni fog!',
    'Base info' => 'Alapadatok',
    'Content' => 'Bejegyzés szövege',
    'Coordinators' => 'Koordinátorok',
    'Create successful' => 'A csoport sikeresen létrehozva',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Delete' => 'Törlés',
    'Delete successful' => 'A csoport sikeresen törölve',
    'Delete unsuccesful' => 'A csoport törlése nem sikerült',
    'Description' => 'Leírás',
    'Email' => 'Email',
    'General' => 'Általános',
    'Group' => 'Csoport',
    'Groups' => 'Csoportok',
    'Join the group' => 'Csatlakozás a csoporthoz',
    'Leave the group' => 'Kilépés a csoportból',
    'Links' => 'Linkek',
    'Main email address (eg. mailing list)' => 'A csoport központi email címe',
    'Members' => 'Tagok',
    'Members: {members}' => 'Tagok száma: {members}',
    'Name' => 'Név',
    'New group' => 'Új csoport',
    'New post' => 'Új bejegyzés',
    'Posts' => 'Bejegyzések',
    'Profile image' => 'Profilkép',
    'Save' => 'Mentés',
    'Something went wrong when you tried to create the post' => 'Hiba történt a bejegyzés létrehozása közben',
    'Something went wrong when you tried to delete the post' => 'Hiba történt a bejegyzés törlése közben',
    'Something went wrong when you tried to join the group' => 'Hiba történt amikor csatlakozni próbáltál a csoporthoz',
    'Something went wrong when you tried to leave the group' => 'Hiba történt amikor megpróbáltad elhagyni a csoportot',
    'Submit' => 'Közzététel',
    'There are no members' => 'Nincsenek tagok',
    'There are no posts' => 'Nincsenek bejegyzések',
    'Title' => 'Cím',
    'Type' => 'Típus',
    'Update' => 'Módosít',
    'Update group: {name}' => 'Csoport módosítása: {name}',
    'Update successful' => 'Sikeresen módosítottad a csoportot',
    'Updated at' => 'Utoljára módosítva',
    'Updated by' => 'Utoljára módosította',
    'Url' => 'Url',
    'User' => 'Felhasználó',
    'You successfully deleted the post' => 'Sikeresen törölted a bejegyzést',
    'You successfully joined the group' => 'Sikeresen csatlakoztál a csoporthoz',
    'You successfully left the group' => 'Sikeresen elhagytad a csoportot',
    'More groups' => 'További csoportok',
    'Group posts' => 'Csoport bejegyzések',
    'You haven\'t joined in any group yet' => 'Még egy csoporthoz sem csatlakoztál.',
];
